projects:
  combined:
    schema: schema.graphql
  base:
    schema: schema-base.graphql
  oeth:
    schema: schema-oeth.graphql
  ousd:
    schema: schema-ousd.graphql
  ogv:
    schema: schema-ogv.graphql
include:
  - types.graphql
