{
 "title": "Aave & Compound Balances",
 "tags": [
  "ousd",
  "aave",
  "compound"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Aave - USDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  balance / 1e6 as balance\nFROM\n  erc20_balance\nwhere\n  $__timeFilter(timestamp) and address = '0xdac17f958d2ee523a2206206994597c13d831ec7' and account = '0x3ed3b47dd13ec9a98b44e6204a523e766b225811'\norder by\n  timestamp asc"
    }
   ]
  },
  {
   "title": "Aave - USDC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  balance / 1e6 as balance\nFROM\n  erc20_balance\nwhere\n  $__timeFilter(timestamp) and address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' and account = '0xbcca60bb61934080951369a648fb03df4f96263c'\norder by\n  timestamp asc"
    }
   ]
  },
  {
   "title": "Aave - DAI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  balance / 1e18 as balance\nFROM\n  erc20_balance\nwhere\n  $__timeFilter(timestamp) and address = '0x6b175474e89094c44da98b954eedeac495271d0f' and account = '0x028171bca77440897b824ca71d1c56cac55b68a3'\norder by\n  timestamp asc"
    }
   ]
  },
  {
   "title": "Compound - USDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  balance / 1e6 as balance\nFROM\n  erc20_balance\nwhere\n  $__timeFilter(timestamp) and address = '0xdac17f958d2ee523a2206206994597c13d831ec7' and account = '0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9'\norder by\n  timestamp asc"
    }
   ]
  },
  {
   "title": "Compound - USDC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  balance / 1e6 as balance\nFROM\n  erc20_balance\nwhere\n  $__timeFilter(timestamp) and address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' and account = '0x39aa39c021dfbae8fac545936693ac917d5e7563'\norder by\n  timestamp asc"
    }
   ]
  },
  {
   "title": "Compound - DAI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  balance / 1e18 as balance\nFROM\n  erc20_balance\nwhere\n  $__timeFilter(timestamp) and address = '0x6b175474e89094c44da98b954eedeac495271d0f' and account = '0x5d3a536e4d6dbd6114cc1ead35777bab948e3643'\norder by\n  timestamp asc"
    }
   ]
  }
 ]
}