{
 "title": "Balancer Pools",
 "tags": [
  "oeth",
  "balancer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "B-rETH-STABLE - 0x1e19cf2d73a72ef1332c882f20534b6519be0276",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH base as (\n  SELECT  \n    timestamp as time, \n    address,\n    balance0 / 1e18 as balance0, \n    balance1 / 1e18 as balance1,\n    (balance0 + balance1) / 1e18 as total\n  FROM balancer_pool_balance\n)\n\nselect\n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\nwhere address = '0x1e19cf2d73a72ef1332c882f20534b6519be0276'\nand $__timeFilter(time) \norder by time"
    }
   ]
  },
  {
   "title": "wstETH-rETH-sfrxETH-BPT - 0x42ed016f826165c2e5976fe5bc3df540c5ad0af7",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH base as (\n  SELECT  \n    timestamp as time, \n    address,\n    balance0 / 1e18 as balance0, \n    balance1 / 1e18 as balance1,\n    balance2 / 1e18 as balance2,\n    balance3 / 1e18 as balance3,\n    (balance1 + balance2 + balance3) / 1e18 as total\n  FROM balancer_pool_balance\n)\n\nselect\n  time,\n  balance1,\n  balance2,\n  balance3,\n  balance1 / nullif(total, 0) as balance1_p,\n  balance2 / nullif(total, 0) as balance2_p,\n  balance3 / nullif(total, 0) as balance3_p\nfrom base\nwhere address = '0x42ed016f826165c2e5976fe5bc3df540c5ad0af7'\nand $__timeFilter(time) \norder by time"
    }
   ]
  },
  {
   "title": "wstETH-WETH-BPT - 0x93d199263632a4ef4bb438f1feb99e57b4b5f0bd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH base as (\n  SELECT  \n    timestamp as time, \n    address,\n    balance0 / 1e18 as balance0, \n    balance1 / 1e18 as balance1,\n    balance2 / 1e18 as balance2,\n    (balance0 + balance2) / 1e18 as total\n  FROM balancer_pool_balance\n)\n\nselect\n  time,\n  balance0,\n  -- balance1,\n  balance2,\n  balance0 / nullif(total, 0) as balance0_p,\n  -- balance1 / nullif(total, 0) as balance1_p,\n  balance2 / nullif(total, 0) as balance2_p\nfrom base\nwhere address = '0x93d199263632a4ef4bb438f1feb99e57b4b5f0bd'\nand $__timeFilter(time) \norder by time"
    }
   ]
  },
  {
   "title": "B-80BAL-20WETH - 0x5c6ee304399dbdb9c8ef030ab642b10820db8f56",
   "type": "timeseries",
   "description": "We're using exchange rates from Chainlink to convert the value of BAL into ETH. Values are shown in ETH.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH base as (\n  SELECT  \n    balancer_pool_balance.timestamp as time, \n    balancer_pool_balance.address,\n    balance0 / 1e18 * exchange_rate.rate / 1e18 as balance0, \n    balance1 / 1e18 as balance1,\n    (balance0 / 1e18 * exchange_rate.rate / 1e18 + balance1 / 1e18) as total\n  FROM balancer_pool_balance\n  INNER JOIN balancer_pool_rate\n    ON balancer_pool_rate.timestamp = balancer_pool_balance.timestamp and balancer_pool_rate.address = balancer_pool_balance.address\n  INNER JOIN exchange_rate\n    ON exchange_rate.timestamp = balancer_pool_balance.timestamp and exchange_rate.pair = 'BAL_ETH'\n)\n\nselect\n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\nwhere address = '0x5c6ee304399dbdb9c8ef030ab642b10820db8f56'\nand $__timeFilter(time) \norder by time"
    }
   ]
  },
  {
   "title": "Gyroscope ECLP wstETH/wETH - 0xf01b0684c98cd7ada480bfdf6e43876422fa1fc1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH base as (\n  SELECT  \n    timestamp as time, \n    address,\n    balance0 / 1e18 as balance0, \n    balance1 / 1e18 as balance1,\n    (balance0 + balance1) / 1e18 as total\n  FROM balancer_pool_balance\n)\n\nselect\n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\nwhere address = '0xf01b0684c98cd7ada480bfdf6e43876422fa1fc1'\nand $__timeFilter(time) \norder by time"
    }
   ]
  }
 ]
}