{
 "title": "Curve Pools",
 "tags": [
  "oeth",
  "ousd",
  "curve"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "ETH Curve Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "factory-v2-298: ETH/OETH - 0x94b17476a93b3262d87b9a326965d1e91f9c13e7",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x94b17476a93b3262d87b9a326965d1e91f9c13e7'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-crypto-210: ETH/rETH - 0x0f3159811670c117c372428d4e69ac32325e4d0f",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x0f3159811670c117c372428d4e69ac32325e4d0f'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "frxeth: ETH/frxETH - 0xa1f8a6807c402e4a15ef4eba36528a3fed24e577",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0xa1f8a6807c402e4a15ef4eba36528a3fed24e577'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-v2-117: WETH/stETH - 0x828b154032950c8ff7cf8085d841723db2696056",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x828b154032950c8ff7cf8085d841723db2696056'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "steth: ETH/stETH - 0xdc24316b9ae028f1497c275eb9192a3ea0f67022",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0xdc24316b9ae028f1497c275eb9192a3ea0f67022'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-crvusd-15: WETH/frxETH - 0x9c3b46c0ceb5b9e304fcd6d88fc50f7dd24b31bc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x9c3b46c0ceb5b9e304fcd6d88fc50f7dd24b31bc'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "stETH-ng: ETH/stETH - 0x21e27a5e5513d6e65c4f830167390997aa84843a",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x21e27a5e5513d6e65c4f830167390997aa84843a'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-v2-274: stETH/frxETH - 0x4d9f9d15101eec665f77210cb999639f760f831e",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x4d9f9d15101eec665f77210cb999639f760f831e'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-crypto-218: rETH/frxETH - 0xe7c6e0a739021cdba7aac21b4b728779eef974d9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0xe7c6e0a739021cdba7aac21b4b728779eef974d9'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-v2-89: rETH/wstETH - 0x447ddd4960d9fdbf6af9a790560d0af76795cb08",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x447ddd4960d9fdbf6af9a790560d0af76795cb08'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "factory-tricrypto-14: wstETH/rETH/sfrxETH - 0x2570f1bd5d2735314fc102eb12fc1afe9e6e7193",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  balance2 / 1e18 as balance2, \n  ((balance0 / 1e18) + (balance1 / 1e18) + (balance2 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x2570f1bd5d2735314fc102eb12fc1afe9e6e7193'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance2,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p,\n  balance2 / nullif(total, 0) as balance2_p\nfrom base\n"
    }
   ]
  },
  { "title": "USD Curve Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "3pool - 0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7 (DAI, USDC, USDT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e6 as balance1, \n  balance2 / 1e6 as balance2, \n  ((balance0 / 1e18) + (balance1 / 1e6) + (balance2 / 1e6)) as total\nFROM curve_pool_balance\nwhere address = '0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance2,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p,\n  balance2 / nullif(total, 0) as balance2_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "OUSDMetapool - 0x87650d7bbfc3a9f10587d7778206671719d9910d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0x87650d7bbfc3a9f10587d7778206671719d9910d'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  },
  {
   "title": "LUSDMetapool - 0xed279fdd11ca84beef15af5d39bb4d4bee23f0ca",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH base as (\nSELECT \n  timestamp as time, \n  balance0 / 1e18 as balance0, \n  balance1 / 1e18 as balance1, \n  ((balance0 / 1e18) + (balance1 / 1e18)) as total\nFROM curve_pool_balance\nwhere address = '0xed279fdd11ca84beef15af5d39bb4d4bee23f0ca'\norder by time\n)\n\nselect \n  time,\n  balance0,\n  balance1,\n  balance0 / nullif(total, 0) as balance0_p,\n  balance1 / nullif(total, 0) as balance1_p\nfrom base\n"
    }
   ]
  }
 ]
}