{
 "title": "Exchange Rates",
 "tags": [
  "oeth",
  "ousd",
  "rates"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"height: 100%; display: flex; justify-content: center; align-items: center;\">\n<span>\n  Note: Some of the data seen here in Grafana \n  and used in alerting uses these rates.\n  It is important to understand the rates we use and validate them.</span>\n<div>"
   }
  },
  { "title": "ETH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Rate - ETH_USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH' and quote = 'USD'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "Rate - ETH_sfrxETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH' and quote = 'sfrxETH'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "Rate - ETH_frxETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH' and quote = 'frxETH'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "Rate - ETH_rETH",
   "type": "timeseries",
   "description": "This rate is derived from the rETH balancer pool.\nhttps://app.balancer.fi/#/ethereum/pool/0x1e19cf2d73a72ef1332c882f20534b6519be0276000200000000000000000112",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH' and quote = 'rETH'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "Rate - ETH_WETH",
   "type": "timeseries",
   "description": "We currently assume 1:1 between ETH and WETH.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH' and quote = 'WETH'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "Rate - ETH_stETH",
   "type": "timeseries",
   "description": "This rate is derived from the stETH balancer pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH' and quote = 'stETH'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "Rate - All (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate / case when quote = 'USD' then 1e8 else 1e18 end as rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'ETH'\norder by timestamp asc"
    }
   ]
  },
  {
   "title": "USD (None)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - All (USD) - Currently None",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp as time,\n  pair,\n  rate\nFROM exchange_rate \nWHERE $__timeFilter(timestamp) AND base = 'USD'\norder by timestamp asc"
      }
     ]
    }
   ]
  }
 ]
}