{
 "title": "OETH Dashboard",
 "tags": [ "oeth" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Holder Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Holder Counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH date_series AS (\n    SELECT generate_series(MIN(DATE(timestamp)), MAX(DATE(timestamp)), '1 day')::date AS date\n    FROM erc20_balance\n),\ngrouped_data AS (\n    SELECT \n        address,\n        account,\n        DATE(timestamp) as entry_date,\n        balance,\n        ROW_NUMBER() OVER (PARTITION BY address, account, DATE(timestamp) ORDER BY timestamp DESC) as rn\n    FROM \n        erc20_balance \n    WHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n)\nSELECT \n    ds.date as time,\n    COUNT(*) FILTER (WHERE balance >= 1e6 AND balance < 1e12) AS \">= .000000000001\",\n    COUNT(*) FILTER (WHERE balance >= 1e12 AND balance < 1e13) AS \">= .000001\",\n    COUNT(*) FILTER (WHERE balance >= 1e13 AND balance < 1e14) AS \">= .00001\",\n    COUNT(*) FILTER (WHERE balance >= 1e14 AND balance < 1e15) AS \">= .0001\",\n    COUNT(*) FILTER (WHERE balance >= 1e15 AND balance < 1e16) AS \">= .001\",\n    COUNT(*) FILTER (WHERE balance >= 1e16 AND balance < 1e17) AS \">= .01\",\n    COUNT(*) FILTER (WHERE balance >= 1e17 AND balance < 1e18) AS \">= .1\",\n    COUNT(*) FILTER (WHERE balance >= 1e18 AND balance < 1e19) AS \">= 1\",\n    COUNT(*) FILTER (WHERE balance >= 1e19 AND balance < 1e20) AS \">= 10\",\n    COUNT(*) FILTER (WHERE balance >= 1e20 AND balance < 1e21) AS \">= 100\",\n    COUNT(*) FILTER (WHERE balance >= 1e21) AS \">= 1000\"\nFROM \n    date_series ds\nLEFT JOIN \n    grouped_data gd ON ds.date = gd.entry_date AND gd.rn = 1\nWHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n  and $__timeFilter(ds.date) \nGROUP BY ds.date\nORDER BY ds.date asc;"
    }
   ]
  },
  {
   "title": "Holder Counts",
   "type": "bargauge",
   "description": "Origin held OETH not yet excluded.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH date_series AS (\n    SELECT generate_series(MIN(DATE(timestamp)), MAX(DATE(timestamp)), '1 day')::date AS date\n    FROM erc20_balance\n),\ngrouped_data AS (\n    SELECT \n        address,\n        account,\n        DATE(timestamp) as entry_date,\n        balance,\n        ROW_NUMBER() OVER (PARTITION BY address, account, DATE(timestamp) ORDER BY timestamp DESC) as rn\n    FROM \n        erc20_balance \n    WHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n)\nSELECT \n    ds.date as time,\n    COUNT(*) FILTER (WHERE balance >= 1e6 AND balance < 1e12) AS \">= .000000000001\",\n    COUNT(*) FILTER (WHERE balance >= 1e12 AND balance < 1e13) AS \">= .000001\",\n    COUNT(*) FILTER (WHERE balance >= 1e13 AND balance < 1e14) AS \">= .00001\",\n    COUNT(*) FILTER (WHERE balance >= 1e14 AND balance < 1e15) AS \">= .0001\",\n    COUNT(*) FILTER (WHERE balance >= 1e15 AND balance < 1e16) AS \">= .001\",\n    COUNT(*) FILTER (WHERE balance >= 1e16 AND balance < 1e17) AS \">= .01\",\n    COUNT(*) FILTER (WHERE balance >= 1e17 AND balance < 1e18) AS \">= .1\",\n    COUNT(*) FILTER (WHERE balance >= 1e18 AND balance < 1e19) AS \">= 1\",\n    COUNT(*) FILTER (WHERE balance >= 1e19 AND balance < 1e20) AS \">= 10\",\n    COUNT(*) FILTER (WHERE balance >= 1e20 AND balance < 1e21) AS \">= 100\",\n    COUNT(*) FILTER (WHERE balance >= 1e21) AS \">= 1000\"\nFROM \n    date_series ds\nLEFT JOIN \n    grouped_data gd ON ds.date = gd.entry_date AND gd.rn = 1\nWHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n  and $__timeFilter(ds.date) \nGROUP BY ds.date\nORDER BY ds.date desc\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Holder TVL %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH date_series AS (\n    SELECT generate_series(MIN(DATE(timestamp)), MAX(DATE(timestamp)), '1 day')::date AS date\n    FROM erc20_balance\n),\ngrouped_data AS (\n    SELECT \n        address,\n        account,\n        DATE(timestamp) as entry_date,\n        balance,\n        ROW_NUMBER() OVER (PARTITION BY address, account, DATE(timestamp) ORDER BY timestamp DESC) as rn\n    FROM \n        erc20_balance \n    WHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n)\nSELECT \n    ds.date as time,\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e6 AND balance < 1e12) / SUM(balance / 1e18) AS \">= .000000000001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e12 AND balance < 1e13) / SUM(balance / 1e18) AS \">= .000001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e13 AND balance < 1e14) / SUM(balance / 1e18) AS \">= .00001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e14 AND balance < 1e15) / SUM(balance / 1e18) AS \">= .0001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e15 AND balance < 1e16) / SUM(balance / 1e18) AS \">= .001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e16 AND balance < 1e17) / SUM(balance / 1e18) AS \">= .01\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e17 AND balance < 1e18) / SUM(balance / 1e18) AS \">= .1\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e18 AND balance < 1e19) / SUM(balance / 1e18) AS \">= 1\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e19 AND balance < 1e20) / SUM(balance / 1e18) AS \">= 10\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e20 AND balance < 1e21) / SUM(balance / 1e18) AS \">= 100\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e21) / SUM(balance / 1e18) AS \">= 1000\"\nFROM \n    date_series ds\nLEFT JOIN \n    grouped_data gd ON ds.date = gd.entry_date AND gd.rn = 1\nWHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n  and $__timeFilter(ds.date) \nGROUP BY ds.date\nORDER BY ds.date asc;"
    }
   ]
  },
  {
   "title": "Holder TVL %",
   "type": "bargauge",
   "description": "Origin held OETH not yet excluded.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH date_series AS (\n    SELECT generate_series(MIN(DATE(timestamp)), MAX(DATE(timestamp)), '1 day')::date AS date\n    FROM erc20_balance\n),\ngrouped_data AS (\n    SELECT \n        address,\n        account,\n        DATE(timestamp) as entry_date,\n        balance,\n        ROW_NUMBER() OVER (PARTITION BY address, account, DATE(timestamp) ORDER BY timestamp DESC) as rn\n    FROM \n        erc20_balance \n    WHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n)\nSELECT \n    ds.date as time,\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e6 AND balance < 1e12) / SUM(balance / 1e18) AS \">= .000000000001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e12 AND balance < 1e13) / SUM(balance / 1e18) AS \">= .000001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e13 AND balance < 1e14) / SUM(balance / 1e18) AS \">= .00001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e14 AND balance < 1e15) / SUM(balance / 1e18) AS \">= .0001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e15 AND balance < 1e16) / SUM(balance / 1e18) AS \">= .001\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e16 AND balance < 1e17) / SUM(balance / 1e18) AS \">= .01\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e17 AND balance < 1e18) / SUM(balance / 1e18) AS \">= .1\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e18 AND balance < 1e19) / SUM(balance / 1e18) AS \">= 1\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e19 AND balance < 1e20) / SUM(balance / 1e18) AS \">= 10\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e20 AND balance < 1e21) / SUM(balance / 1e18) AS \">= 100\",\n    SUM(balance / 1e18) FILTER (WHERE balance >= 1e21) / SUM(balance / 1e18) AS \">= 1000\"\nFROM \n    date_series ds\nLEFT JOIN \n    grouped_data gd ON ds.date = gd.entry_date AND gd.rn = 1\nWHERE address = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\n  and $__timeFilter(ds.date)\nGROUP BY ds.date\nORDER BY ds.date desc\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "OETH General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vault Balances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  frx_eth / 1000000000000000000 as frx_eth,\n  r_eth / 1000000000000000000 as r_eth,\n  st_eth / 1000000000000000000 as st_eth,\n  weth / 1000000000000000000 as weth\nFROM oeth_vault\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OETH Supply",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  total_supply / 1e18 as total_supply,\n  rebasing_supply / 1e18 as rebasing_supply,\n  non_rebasing_supply / 1e18 as non_rebasing_supply\nFROM oeth\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "APY",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  apy7_day_avg,\n  apy14_day_avg,\n  apy30_day_avg,\n  apy\nFROM oethapy\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Yield",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  yield_eth / 1e18 as yield\nFROM o_token_rebase\nWHERE\n  $__timeFilter(\"timestamp\") AND chain_id = 1 AND otoken = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fees",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  fee_eth / 1e18 as fee\nFROM o_token_rebase\nWHERE\n  $__timeFilter(\"timestamp\") AND chain_id = 1 AND otoken = '0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OETH Strategies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Convex ETH+OETH (AMO)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  asset AS metric,\n  balance / 1e18 as balance\nFROM strategy_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  strategy = '0x1827f9ea98e0bf96550b2fc20f7233277fcd7e63'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Frax Staking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  asset AS metric,\n  balance / 1e18 as balance\nFROM strategy_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  strategy = '0x3ff8654d633d4ea0fae24c52aec73b4a20d0d0e5'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Morpho Aave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  asset AS metric,\n  balance / 1e18 as balance\nFROM strategy_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  strategy = '0xc1fc9e5ec3058921ea5025d703cbe31764756319'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Aura Balancer Metapool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  asset AS metric,\n  balance / 1e18 as balance\nFROM strategy_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  strategy = '0x49109629ac1deb03f2e9b2fe2ac4a623e0e7dfdc'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "OETH/ETH Curve Metapool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0 / 1e18 as balance0,\n  balance1 / 1e18 as balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0x94b17476a93b3262d87b9a326965d1e91f9c13e7'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Balance %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0,\n  balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0x94b17476a93b3262d87b9a326965d1e91f9c13e7'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "WETH/stETH Curve Metapool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0 / 1e18 as balance0,\n  balance1 / 1e18 as balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0x828b154032950c8ff7cf8085d841723db2696056'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Balance %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0,\n  balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0x828b154032950c8ff7cf8085d841723db2696056'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ETH/stETH Curve Metapool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0 / 1e18 as balance0,\n  balance1 / 1e18 as balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0xdc24316b9ae028f1497c275eb9192a3ea0f67022'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Balance %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0,\n  balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0xdc24316b9ae028f1497c275eb9192a3ea0f67022'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ETH/frxETH Curve Metapool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0 / 1e18 as balance0,\n  balance1 / 1e18 as balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0xa1f8a6807c402e4a15ef4eba36528a3fed24e577'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Balance %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0,\n  balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0xa1f8a6807c402e4a15ef4eba36528a3fed24e577'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ETH/rETH Curve Metapool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0 / 1e18 as balance0,\n  balance1 / 1e18 as balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0x0f3159811670c117c372428d4e69ac32325e4d0f'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Balance %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  balance0,\n  balance1\nFROM curve_pool_balance\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  address = '0x0f3159811670c117c372428d4e69ac32325e4d0f'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OETH Strategies (Old method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Curve AMO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  eth_owned / 1e18 as eth_owned,\n  oeth_owned / 1e18 as oeth_owned\nFROM oeth_curve_lp\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "FraxETH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sfrx_eth / 1e18 as sfrx_eth\nFROM oeth_frax_staking\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Aura Balancer Metapool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  r_eth / 1e18 as r_eth,\n  weth / 1e18 as weth\nFROM oeth_balancer_meta_pool_strategy\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}