{
 "title": "OGN / OGV Distribution",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Team Wallet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OGN Balance (Team)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n    timestamp as time,\n    case address\n        when '0x8207c1ffc5b6804f6024322ccf34f29c3541ae26' then 'OGN'\n        when '0x9c354503c38481a7a7a51629142963f98ecc12d0' then 'OGV'\n        else address end,\n    balance / 1e18 as balance\nfrom erc20_balance\nwhere account = '0x2eae0cae2323167abf78462e0c0686865c67a655'\n  and address in ('0x8207c1ffc5b6804f6024322ccf34f29c3541ae26')\n  and $__timeFilter(timestamp) \norder by time"
    }
   ]
  },
  {
   "title": "OGV Balance (Team)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n    timestamp as time,\n    case address\n        when '0x8207c1ffc5b6804f6024322ccf34f29c3541ae26' then 'OGN'\n        when '0x9c354503c38481a7a7a51629142963f98ecc12d0' then 'OGV'\n        else address end,\n    balance / 1e18 as balance\nfrom erc20_balance\nwhere account = '0x2eae0cae2323167abf78462e0c0686865c67a655'\n  and address in ('0x9c354503c38481a7a7a51629142963f98ecc12d0')\n  and $__timeFilter(timestamp) \norder by time"
    }
   ]
  },
  { "title": "Investor Wallet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OGN Balance (Investor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n    timestamp as time,\n    case address\n        when '0x8207c1ffc5b6804f6024322ccf34f29c3541ae26' then 'OGN'\n        when '0x9c354503c38481a7a7a51629142963f98ecc12d0' then 'OGV'\n        else address end,\n    balance / 1e18 as balance\nfrom erc20_balance\nwhere account = '0xfe730b3cf80ca7b31905f70241f7c786baf443e3'\n  and address in ('0x8207c1ffc5b6804f6024322ccf34f29c3541ae26')\n  and $__timeFilter(timestamp) \norder by time"
    }
   ]
  },
  {
   "title": "OGV Balance (Investor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n    timestamp as time,\n    case address\n        when '0x8207c1ffc5b6804f6024322ccf34f29c3541ae26' then 'OGN'\n        when '0x9c354503c38481a7a7a51629142963f98ecc12d0' then 'OGV'\n        else address end,\n    balance / 1e18 as balance\nfrom erc20_balance\nwhere account = '0xfe730b3cf80ca7b31905f70241f7c786baf443e3'\n  and address in ('0x9c354503c38481a7a7a51629142963f98ecc12d0')\n  and $__timeFilter(timestamp) \norder by time"
    }
   ]
  }
 ]
}