{
 "title": "OUSD Strategy Earnings",
 "tags": [ "ousd" ],
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  { "title": "OUSD Strategies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OUSD Maker DSR - Earnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, earnings_change / 1000000000000000000 as earnings_change, balance / 1000000000000000000 as balance\nFROM strategy_daily_yield\nWHERE strategy = '0x6b69b755c629590ed59618a2712d8a2957ca98fc'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OUSD Maker DSR - APY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -- earnings_change / 1000000000000000000 as earnings_change,\n  apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x6b69b755c629590ed59618a2712d8a2957ca98fc'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latest APY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x6b69b755c629590ed59618a2712d8a2957ca98fc'\nORDER BY timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "OUSD Flux - Earnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, earnings_change / 1000000000000000000 as earnings_change, balance / 1000000000000000000 as balance\nFROM strategy_daily_yield\nWHERE strategy = '0x76bf500b6305dc4ea851384d3d5502f1c7a0ed44'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OUSD Flux - APY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -- earnings_change / 1000000000000000000 as earnings_change,\n  apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x76bf500b6305dc4ea851384d3d5502f1c7a0ed44'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latest APY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x76bf500b6305dc4ea851384d3d5502f1c7a0ed44'\nORDER BY timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "OUSD Morpho Aave - Earnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, earnings_change / 1000000000000000000 as earnings_change, balance / 1000000000000000000 as balance\nFROM strategy_daily_yield\nWHERE strategy = '0x79f2188ef9350a1dc11a062cca0abe90684b0197'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OUSD Morpho Aave - APY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -- earnings_change / 1000000000000000000 as earnings_change,\n  apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x79f2188ef9350a1dc11a062cca0abe90684b0197'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latest APY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x79f2188ef9350a1dc11a062cca0abe90684b0197'\nORDER BY timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "OUSD Morpho Compound - Earnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, earnings_change / 1000000000000000000 as earnings_change, balance / 1000000000000000000 as balance\nFROM strategy_daily_yield\nWHERE strategy = '0x5a4eee58744d1430876d5ca93cab5ccb763c037d'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OUSD Morpho Compound - APY by Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -- earnings_change / 1000000000000000000 as earnings_change,\n  apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x5a4eee58744d1430876d5ca93cab5ccb763c037d'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latest APY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x5a4eee58744d1430876d5ca93cab5ccb763c037d'\nORDER BY timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "OUSD Convex OUSD+3Crv (AMO) - Earnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, earnings_change / 1000000000000000000 as earnings_change, balance / 1000000000000000000 as balance\nFROM strategy_daily_yield\nWHERE strategy = '0x89eb88fedc50fc77ae8a18aad1ca0ac27f777a90'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OUSD Convex OUSD+3Crv (AMO) - APY by Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -- earnings_change / 1000000000000000000 as earnings_change,\n  apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x89eb88fedc50fc77ae8a18aad1ca0ac27f777a90'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latest APY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x89eb88fedc50fc77ae8a18aad1ca0ac27f777a90'\nORDER BY timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "OUSD Aave - Earnings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, earnings_change / 1000000000000000000 as earnings_change, balance / 1000000000000000000 as balance\nFROM strategy_daily_yield\nWHERE strategy = '0x5e3646a1db86993f73e6b74a57d8640b69f7e259'\n  and $__timeFilter(timestamp)\norder by timestamp"
    }
   ]
  },
  {
   "title": "OUSD Aave - APY by Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -- earnings_change / 1000000000000000000 as earnings_change,\n  apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x5e3646a1db86993f73e6b74a57d8640b69f7e259'\n  and $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latest APY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS apy,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS apy7,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS apy14,\n  AVG(apy) OVER(ORDER BY timestamp ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS apy30\nFROM\n  strategy_daily_yield \n  where strategy = '0x5e3646a1db86993f73e6b74a57d8640b69f7e259'\nORDER BY timestamp desc\nlimit 1"
    }
   ]
  }
 ]
}