{
 "title": "OUSD Dashboard",
 "tags": [ "ousd" ],
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "OUSD General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vault Balances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  dai / 1000000000000000000 as dai,\n  usdc / 1000000000000000000 as usdc,\n  usdt / 1000000000000000000 as usdt\nFROM ousd_vault\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "OUSD Supply",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  total_supply / 1e18 as total_supply,\n  rebasing_supply / 1e18 as rebasing_supply,\n  non_rebasing_supply / 1e18 as non_rebasing_supply\nFROM ousd\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "APY",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  apy7_day_avg,\n  apy14_day_avg,\n  apy30_day_avg,\n  apy\nFROM ousdapy\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp as time, apy, apy7_day_avg, apy14_day_avg, apy30_day_avg from ousdapy order by id desc limit 1"
    }
   ]
  },
  {
   "title": "Yield Accrual",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  yield / 1e18 as yield\nFROM ousd_rebase\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fee Accrual",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  fee / 1e18 as fee\nFROM ousd_rebase\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  { "title": "OUSD Strategy Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "OUSD Convex OUSD+3Crv (AMO)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as time, \nasset, \nbalance / case asset \n  when '0x6b175474e89094c44da98b954eedeac495271d0f' then 1e18 \n  when '0xdac17f958d2ee523a2206206994597c13d831ec7' then 1e6 \n  when '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' then 1e6 \nend as balance\nFROM strategy_balance where strategy = '0x89eb88fedc50fc77ae8a18aad1ca0ac27f777a90'"
    }
   ]
  },
  {
   "title": "OUSD Flux",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as time, \nasset, \nbalance / case asset \n  when '0x6b175474e89094c44da98b954eedeac495271d0f' then 1e18 \n  when '0xdac17f958d2ee523a2206206994597c13d831ec7' then 1e6 \n  when '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' then 1e6 \nend as balance\nFROM strategy_balance where strategy = '0x76bf500b6305dc4ea851384d3d5502f1c7a0ed44'\norder by timestamp, asset desc"
    }
   ]
  },
  {
   "title": "OUSD Maker DSR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as time, \nasset, \nbalance / case asset \n  when '0x6b175474e89094c44da98b954eedeac495271d0f' then 1e18 \n  when '0xdac17f958d2ee523a2206206994597c13d831ec7' then 1e6 \n  when '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' then 1e6 \nend as balance\nFROM strategy_balance where strategy = '0x6b69b755c629590ed59618a2712d8a2957ca98fc'\norder by timestamp, asset desc"
    }
   ]
  },
  {
   "title": "OUSD Morpho Compound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as time, \nasset, \nbalance / case asset \n  when '0x6b175474e89094c44da98b954eedeac495271d0f' then 1e18 \n  when '0xdac17f958d2ee523a2206206994597c13d831ec7' then 1e6 \n  when '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' then 1e6 \nend as balance\nFROM strategy_balance where strategy = '0x5a4eee58744d1430876d5ca93cab5ccb763c037d'\norder by timestamp, asset desc"
    }
   ]
  },
  {
   "title": "OUSD Morpho Aave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as time, \nasset, \nbalance / case asset \n  when '0x6b175474e89094c44da98b954eedeac495271d0f' then 1e18 \n  when '0xdac17f958d2ee523a2206206994597c13d831ec7' then 1e6 \n  when '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' then 1e6 \nend as balance\nFROM strategy_balance where strategy = '0x79f2188ef9350a1dc11a062cca0abe90684b0197'\norder by timestamp, asset desc"
    }
   ]
  },
  {
   "title": "OUSD Aave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as time, \nasset, \nbalance / case asset \n  when '0x6b175474e89094c44da98b954eedeac495271d0f' then 1e18 \n  when '0xdac17f958d2ee523a2206206994597c13d831ec7' then 1e6 \n  when '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' then 1e6 \nend as balance\nFROM strategy_balance where strategy = '0x5e3646a1db86993f73e6b74a57d8640b69f7e259'"
    }
   ]
  }
 ]
}