name: Release squid version
on:
  push:
    branches:
      - 'v[0-9]+'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install squid CLI
        run: npm i -g @subsquid/cli

      - name: npm install
        run: npm i

      - name: update squid.yml
        run: |
          # Get the branch name from GitHub
          BRANCH_NAME=${{ github.ref_name }}

          # Extract the version from the branch name (assuming format 'vXX')
          VERSION=$(echo $BRANCH_NAME | sed 's/^v//')

          # Update the version in squid.yaml
          sed -i "s/^version: .*/version: $VERSION/" squid.yaml

          # Optional: Print the updated version for verification
          echo "Updated squid.yaml version to: $VERSION"

      - name: Authenticate to squid
        env:
          API_TOKEN: ${{ secrets.SQUID_API_TOKEN }}
        run: sqd auth -k $API_TOKEN

      - name: Build and deploy squid
        run: sqd build && sqd deploy . -o origin --no-stream-logs --allow-update
